kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-slave" 
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-slave-test:latest'
  source: 
    dockerfile: >-
      FROM docker.io/openshift/jenkins-slave-base-centos7

      RUN yum -y install gcc rpm-build rpm-devel rpmlint make python bash
      coreutils diffutils patch rpmdevtools && yum -y clean all
  strategy:
    type: Docker
